# JARVIS Configuration

[General]
OutputPath = "<ABSOLUTE_OUTPUT_PATH>"
ServerPort = 8080

[Spotify]
Enabled = true
Output = true
AutoLogin = true
PollingFrequency = "5s"
ClientID = "<SPOTIFY_CLIENT_ID>"
ClientSecret = "<SPOTIFY_CLIENT_SECRET>"
Callback = "/callbackSpotify"
TruncateTrackLength = 85
TruncateTrackRunes = "..."

[Twitch]
Enabled = true
Output = true
PollingFrequency = "5s"
ClientID = "<TWITCH_CLIENT_ID>"
ClientSecret = "<TWITCH_CLIENT_SECRET>"
ChannelID = <TWITCH_CHANNEL_ID>
LastFollowersCount = 10
ChatEnabled = true
ChatEcho = true
ChatName = "JARVIS"
ChatToken = "<OAUTH TOKEN>"
ChatChannel = "#reapazor"

[WorkingOn]
Enabled = true
Output = true